### ISSUE TITLE
Single ZIP for releases

### ISSUE THREAD

**Issue by Lexus89** [ropnop/impacket_static_binaries#5]
First of all good work on this! Downloading all binaries would be much easier if they were inside a single zip though

**Comment by ropnop** [comment]
Good idea - done! I'm keeping the singular binaries in there because I think that's easier to only download the one I need at the time, but there is now a ZIP of the Windows binaries and a tarball of the linux ones

28d20721b03e5d88d28f3110eff1af30741e419b
